language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database saudecontrolada_test;' -U postgres
