language: ruby
rvm:
  - 2.1.2
env:
  global:
    secure: sA95+EfyLvZvHklBvyWeQGLAWP4BWu7F39YJ791BtytrllTvvIvuGosQAiPn3PbCwGAchdaZiTReJJ+N15tTb8+hugr8UVJlRDWZQHYFJ68ROt4qxyyo6TAhkq8LovZXNv5RkW/8KlQSkpJUJBFY53bShgoO/jedsTCSOSkxDs3613tAve8byAHNpb1Nexmq8y56sYGQREF/JEj4F5SRXie5FSyqXOoAR4lDH0U/ApWHM6W8yVv6NGcRZHpXx40BQr9Rl8b1ugWBMJpXDw7q+RC8uesEopj6B49TGkiWJdH3kecZFzhKZEePUJEddB75ovx5eg9+0XP78WjZxP+H4ZqV2hgqD1amrHZF5iC44HC3egRLhQ4N+5SN4NGypSiNo4gIUrUTClXoI1sFQ9MbM0MQrFbIK95cwclFRqLB3irnT78BCuw5Z8+duk/MKN1W3LsTcuU1IW7upR7vzaRxrnbWVZi2hfN2+5FjVnX9Ja49L0LXgXbLGX1YFaodbFmpipWuBRXDLk4/IxW6/up0kwI1wtZouVSpL0y6MaIh6l59kcXnYS+f5+O9usmAPBKfT5K3f2CIOwNb5LQqEumJNOVBpY6eyDJY035qcxRNsiTUfWpFw6J4U+tRBG4H/bIqQZGVUOdtr2hRFSS4rk6upTPy8fJC+vN4rzOXfxeiGrA=
