default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: saudecontrolada

test:
  <<: *default
  database: saudecontrolada_test
  username: travis

production:
  <<: *default
  database: saudecontrolada_production
  username: <%= ENV['SAUDECONTROLADA_DATABASE_USERNAME'] %>
  password: <%= ENV['SAUDECONTROLADA_DATABASE_PASSWORD'] %>
