default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: saudecontrolada

test:
  <<: *default
  database: saudecontrolada_test
  username: <%= ENV['DATABASE_TEST_USERNAME'] %>

production:
  <<: *default
  database: saudecontrolada
  username: <%= ENV['DATABASE_PROD_USERNAME'] %>
  password: <%= ENV['DATABASE_PROD_PASSWORD'] %>
