default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: Melo
  password:

development:
  <<: *default
  database: saudecontrolada

test:
  <<: *default
  database: saudecontrolada_test

production:
  <<: *default
  database: saudecontrolada
  username: <%= ENV['DATABASE_PROD_USERNAME'] %>
  password: <%= ENV['DATABASE_PROD_PASSWORD'] %>
