default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: saudecontrolada

test:
  <<: *default
  database: saudecontrolada_test

production:
  <<: *default
  database: saudecontrolada_production
  username: <%= ENV['SAUDECONTROLADA_DATABASE_USERNAME'] %>
  password: <%= ENV['SAUDECONTROLADA_DATABASE_PASSWORD'] %>
