common: &default_settings
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  app_name: 'Saúde Controlada'
  log_level: info
development:
  <<: *default_settings
  app_name: Saúde Controlada (Development)
  developer_mode: true
test:
  <<: *default_settings
  monitor_mode: false
staging:
  <<: *default_settings
  app_name: Saúde Controlada (Staging)
production:
  <<: *default_settings
