development:
  mailer_from: <%= ENV['EMAIL_USER_NAME'] %>
  mailer_host: <%= ENV['MAILER_HOST'] %>
  mailer_sender: <%= ENV['MAILER_SENDER'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_token_devise: <%= ENV['SECRET_TOKEN_DEVISE'] %>
test:
  mailer_from: <%= ENV['EMAIL_USER_NAME'] %>
  mailer_host: <%= ENV['MAILER_HOST'] %>
  mailer_sender: <%= ENV['MAILER_SENDER'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_token_devise: <%= ENV['SECRET_TOKEN_DEVISE'] %>
production:
  email_user_name: <%= ENV['EMAIL_USER_NAME'] %>
  email_password: <%= ENV['EMAIL_PASSWORD'] %>
  mailer_from: <%= ENV['EMAIL_USER_NAME'] %>
  mailer_host: <%= ENV['MAILER_HOST'] %>
  mailer_sender: <%= ENV['MAILER_SENDER'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_token_devise: <%= ENV['SECRET_TOKEN_DEVISE'] %>
