#encoding: utf-8
development:
  delayed_job_web_path: 'delayed_job'
  mailer_from: 'suporte@saudecontrolada.com.br'
  mailer_host: 'localhost:3000'
  mailer_sender: 'Saúde Controlada <suporte@saudecontrolada.com.br>'
  secret_key_base: '520af2e300468f46d886fe959ba2fd805ab05be97df2f3fe18db76e1a851fac2da37af468c2c7f1c0947785beb01d5ad438881d0df0594dc87c7e951ebb0bbc2'
  secret_token_devise: 'ad69c5ef52b16f990e549a6b84cf441f6d3199f91ce75e52d9635eaa493bb1a9505a585d973a20e84971b9ee698f85a1e9e609bc0f516df40961ea207d30b8ff'
test:
  delayed_job_web_path: 'delayed_job'
  mailer_from: 'suporte@saudecontrolada.com.br'
  mailer_host: 'localhost:3000'
  mailer_sender: 'Saúde Controlada <suporte@saudecontrolada.com.br>'
  secret_key_base: '3149df769049dec669ffcbe58150db62edb7b4818b96c8f20ffce32cfc2b25375336f7ff5a884542da15eec5c501d8418ff7f3d662ebe45a660e15241a17552b'
  secret_token_devise: 'b1062f7ce3632205bfd71f7d3a5d6284b6d7afb048660df1fa9375f7bba71744438a6c23a6c9f6718bca09f5ed79318939c633350cda9a387029003ea6b3dde1'
production:
  delayed_job_web_path: <%= ENV['DELAYED_JOB_WEB_PATH'] %>
  email_user_name: <%= ENV['EMAIL_USER_NAME'] %>
  email_password: <%= ENV['EMAIL_PASSWORD'] %>
  mailer_from: <%= ENV['EMAIL_USER_NAME'] %>
  mailer_host: <%= ENV['MAILER_HOST'] %>
  mailer_sender: <%= ENV['MAILER_SENDER'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

  secret_token_devise: <%= ENV['SECRET_TOKEN_DEVISE'] %>
