development:
#  mailer_from: 'suporte@condominiosimples.com.br'
#  mailer_host: 'localhost:3000'
#  mailer_sender: 'Condomínio Simples <suporte@condominiosimples.com.br>'
  secret_key_base: 633e8fd4298d7ae3c97bbb149c74b211f440bee47db97a67bb4d8402b6f3b3fef9898116b7de615224357c3405faaf34b3c07ed297eb1c86a8237692819b962a
#  secret_token_devise: 71456e05261d9dc3477108b2bd0e92ccd5366b81b89f5aef0cc77f7ace46fbded453467a38c7e38d35dbb0d37288d66fb30487938f2bffdc3756f1f7ff056b67
test:
#  mailer_from: 'suporte@condominiosimples.com.br'
#  mailer_host: 'localhost:3000'
#  mailer_sender: 'Condomínio Simples <suporte@condominiosimples.com.br>'
  secret_key_base: df0422ecd54b68e84f0a0bff5b1c81650f225217be6d30535d8d47a94ba64bc849a590e92b2b684948c828ad8fe13f61dfd54374f19aa5ecff7da2d8bf8ded12
#  secret_token_devise: 296a25310b27c46302f0faae9268e5a281c6b3690ff794e1c7411856cac49b433fba821d4be84428e3c782b446471a8aa2e6d3fc1ff57e1b9eb6855bf14e9063
production:
#  email_user_name: <%= ENV['EMAIL_USER_NAME'] %>
#  email_password: <%= ENV['EMAIL_PASSWORD'] %>
#  mailer_from: 'suporte@condominiosimples.com.br'
#  mailer_host: <%= ENV['MAILER_HOST'] %>
#  mailer_sender: 'Condomínio Simples <suporte@condominiosimples.com.br>'
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
#  secret_token_devise: <%= ENV['SECRET_TOKEN_DEVISE'] %>
