development:
  allowed_origin: 'http://localhost:3001'
  email_username: 'email@exemplo.com.br'
  exception_recipients: 'exception@exemplo.com.br'
  mailer_host: 'localhost:3000'
  mailer_sender: 'Saúde Controlada <email@exemplo.com.br>'
  secret_key_base: 6f1033bf656c7a58af245d89d1a58bb5643243b9de557b3e12b739a55d4b0901d1e4be81bca4e0ec3f4fe8b81f46da4012b1523557e742d1734bb56f8de95b5d

test:
  email_username: 'email@exemplo.com.br'
  exception_recipients: 'exception@exemplo.com.br'
  mailer_host: 'localhost:3000'
  mailer_sender: 'Saúde Controlada <email@exemplo.com.br>'
  secret_key_base: 4bb49b6e64a903320883ef7ecba9f14eaac15b0a7bea75dcc2702d289eb8032b6654686d2b295911c88d62b119962a2c82305c270067e2b739ece382d6ff694d

production:
  allowed_origin: <%= ENV['ALLOWED_ORIGIN'] %>
  email_username: <%= ENV['EMAIL_USERNAME'] %>
  email_password: <%= ENV['EMAIL_PASSWORD'] %>
  exception_recipients: <%= ENV['EXCEPTION_RECIPIENTS'] %>
  mailer_host: <%= ENV['MAILER_HOST'] %>
  mailer_sender: <%= ENV['MAILER_SENDER'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
